dev.server: docker.alta-group.ru

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notification_center
    username: ******************
    password: ******************
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cloud.alta-group.ru/iam/auth/realms/altacloud-dev
          jwk-set-uri: https://cloud.alta-group.ru/iam/auth/realms/altacloud-dev/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: ******************
            client-secret: ******************
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: https://cloud.alta-group.ru/iam/auth/realms/altacloud-dev
            token-uri: https://cloud.alta-group.ru/iam/auth/realms/altacloud-dev/protocol/openid-connect/token

  cloud:
    stream:
      kafka:
        binder:
          brokers: docker.alta-group.ru:19092,docker.alta-group.ru:19093,docker.alta-group.ru:19094
          autoCreateTopics: true
          minPartitionCount: 3
          replicationFactor: 2
          consumerProperties:
            schema.registry.url: http://${dev.server}:8081
            auto.register.schemas: false
            use.latest.version: true
            specific.avro.reader: true
            value.subject.name.strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy
            value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
        bindings:
          consumeStationNotification-in-0:
            consumer:
              enableDlq: true
              dlqName: test.altacloud.notifications.stations.avro.dlq
          consumeUserNotification-in-0:
            consumer:
              enableDlq: true
              dlqName: test.altacloud.notifications.users.avro.dlq
      bindings:
        consumeUserEvent-in-0:
          group: ${spring.application.name}
          destination: test.altacloud.users.cdc.avro,test.altacloud.dealers.cdc.avro
        consumeStationEvent-in-0:
          group: ${spring.application.name}
          destination: test.altacloud.binding.stations.avro
        consumeStationNotification-in-0:
          group: ${spring.application.name}
          destination: test.altacloud.notifications.stations.avro
        consumeUserNotification-in-0:
          group: ${spring.application.name}
          destination: test.altacloud.notifications.users.avro

  mail:
    username: ******************
    password: ******************
    host: smtp.beget.ru
    port: 465
    properties:
      smtp:
        auth: true
        socketFactory:
          port: 465
          class: javax.net.ssl.SSLSocketFactory

springdoc:
  show-actuator: false
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

errors-service:
  url: localhost:8090/errors/{code}