spring:
  datasource:
    url: jdbc:postgresql://******************
    username: ******************
    password: ******************
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-on-migrate: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cloud.alta-group.ru/iam/auth/realms/altacloud-stage
          jwk-set-uri: https://cloud.alta-group.ru/iam/auth/realms/altacloud-stage/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: ******************
            client-secret: ******************
            authorization-grant-type: client_credentials
        provider:
          keycloak:
            issuer-uri: https://cloud.alta-group.ru/iam/auth/realms/altacloud-stage
            token-uri: https://cloud.alta-group.ru/iam/auth/realms/altacloud-stage/protocol/openid-connect/token

  cloud:
    stream:
      kafka:
        binder:
          brokers: confluent-cp-kafka-headless.kafka:9092
          autoCreateTopics: true
          minPartitionCount: 3
          replicationFactor: 2
          consumerProperties:
            schema.registry.url: http://:8081
            auto.register.schemas: false
            use.latest.version: true
            specific.avro.reader: true
            value.subject.name.strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy
            value.deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
        bindings:
          consumeStationNotification-in-0:
            consumer:
              enableDlq: true
              dlqName: staging.altacloud.notifications.stations.avro.dlq
          consumeUserNotification-in-0:
            consumer:
              enableDlq: true
              dlqName: staging.altacloud.notifications.users.avro.dlq
      bindings:
        consumeUserEvent-in-0:
          group: ${spring.application.name}
          destination: staging.altacloud.users.cdc.avro,staging.altacloud.dealers.cdc.avro
        consumeStationEvent-in-0:
          group: ${spring.application.name}
          destination: staging.altacloud.binding.stations.avro
        consumeStationNotification-in-0:
          group: ${spring.application.name}
          destination: staging.altacloud.notifications.stations.avro
        consumeUserNotification-in-0:
          group: ${spring.application.name}
          destination: staging.altacloud.notifications.users.avro

  mail:
    username: ******************
    password: ******************
    host: smtp.beget.ru
    port: 465
    properties:
      smtp:
        auth: true
        socketFactory:
          port: 465
          class: javax.net.ssl.SSLSocketFactory

springdoc:
  show-actuator: false
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

errors-service:
  url: altacloud-v2-errors:8090/errors/{code}