package ru.altagroup.notificationcenter.entities;

public enum MessageType {
    //PASSWORD_NOTIFICATION
    USER_EVENT,
    SUBSCRIPTION_NOTIFICATION_MAINTAINER,
    SUBSCRIPTION_NOTIFICATION_USER,
    UNSUBSCRIPTION_NOTIFICATION_MAINTAINER,
    UNSUBSCRIPTION_NOTIFICATION_USER,
    ERROR_EVENT,
    MAINTAINER_NOTIFICATION,
    LICENCE_NOTIFICATION_MAINTAINER,
    STATION_EVENT
}
